import { Button } from './ui/button'

const ASSETS = '/assets/figma'

function FigmaIcon({ name, alt = '' }: { name: string; alt?: string }) {
  return <img src={`${ASSETS}/${name}`} alt={alt} />
}

export function SiteFooter() {
  return <footer className="site-footer"><section className="footer-top"><div className="footer-benefit"><span>W</span><h2>Segurança da carteira</h2><p>Proteja sua carteira e colecione arte digital verificada com confiança.</p></div><div className="footer-benefit"><span>C</span><h2>Criadores em destaque</h2><p>Conheça artistas, estúdios e comunidades que moldam a cultura digital na rede.</p></div><div className="footer-benefit"><span>D</span><h2>Alertas de lançamentos</h2><p>Receba calendários de cunhagem, novidades de listas de acesso e análises do mercado.</p></div><div className="newsletter"><h2>Antecipe-se ao próximo lançamento</h2><form onSubmit={(event) => event.preventDefault()}><input type="email" aria-label="Seu e-mail" placeholder="digite seu e-mail..." /><Button type="submit" size="sm">Enviar</Button></form><p>Receba lançamentos selecionados, histórias de criadores e novidades do mercado.</p></div></section><section className="footer-contact"><b>KURIO</b><p>Feito para colecionadores,<br />criadores e cultura</p><a href="mailto:contato@email.com">contato@email.com</a><p>+55 11 4002 8922</p></section><section className="footer-links"><div><h2>Meu perfil</h2><a href="#inicio">Meu perfil</a><a href="#inicio">Minha coleção</a><a href="#inicio">Atividade</a><a href="#inicio">Estúdio do criador</a><a href="#inicio">Lista de interesse</a></div><div><h2>Central de ajuda</h2><a href="#inicio">Central de ajuda</a><a href="#inicio">Como comprar NFTs</a><a href="#inicio">Carteira e segurança</a><a href="#inicio">Política do mercado</a><a href="#inicio">Denunciar item</a></div><div><h2>Coleções</h2><a href="#mercado">Arte digital</a><a href="#mercado">Fotografia</a><a href="#mercado">Música</a><a href="#mercado">Arte 3D</a><a href="#mercado">Utilidade</a></div><div className="footer-social"><h2>Redes sociais</h2><div>{['social-facebook.svg', 'social-instagram.svg', 'social-twitter.svg', 'social-linkedin.svg', 'social-youtube.svg'].map((icon) => <a href="#inicio" key={icon}><FigmaIcon name={icon} /></a>)}</div><h2>Carteiras compatíveis</h2><p>METAMASK&nbsp; • &nbsp;WALLETCONNECT&nbsp; • &nbsp;COINBASE</p></div></section><p className="copyright">© 2026 Kurio. Propriedade digital para todos.</p></footer>
}
